spdlog: Autospec creation for update from version 1.10.0 to version 1.11.0
Aengus.Jiang (2):
      clean code, clean up the warning
      fix error: cannot bind lvale to right reference

Alexander Shpilkin (2):
      Allow absolute CMAKE_INSTALL_LIBDIR
      Reflect CMAKE_INSTALL_INCLUDEDIR in pkg-config

Alexandre Pereira Nunes (1):
      Remove redundant std::move at return (triggers -Wredundant-move in Gcc, at least)

Charles Milette (10):
      Switch to vformat_to
      Add missing include
      Fix bad #ifdef
      Actually fix bad #ifdef
      Fix conversion from fmt::memory_buffer to fmt::string_view
      Remove fmt_helper.h include from logger.h
      Add fmt_helper.h include to includes.h and os-inl.h
      Address PR review comments
      Replace fmt_helper::to_string by a macro
      Remove fmt_helper::to_string

Daniil (1):
      Replace iterator difference with std::distance

David Roman (1):
      fix clone async test

Gabi Melman (12):
      Remove comment
      Fixed move in ringnuffer_sink
      Update common.h
      Update README.md
      Fix #2419 by documenting the set_pattern behaviour
      Fix #2434
      Update appveyor.yml
      Update appveyor.yml
      chrono.h: Remove warning suppression
      Update ci.yml
      Update ci.yml
      Version 1.11.0

Hector PHARAM (1):
      Removed doc "(shared not supported in windows yet)"

Jan Engelhardt (1):
      build: expand SOVERSION to not give false illusion of compatibility

Jeeyong Um (3):
      Allow overriding need_localtime for custom formatter
      Copy the value of need_localtime when cloning pattern_formatter
      Set eol to the test for overriding need_localtime

John Armstrong (1):
      Add FMT_STRING to allow compilation with FMT_ENFORCE_COMPILE_STRING

Kevin Slattery (3):
      C++14 build fixes for older gcc #2333
      Remove new macro, update example with correct way to specify fmt lib namespace when fmt_lib namespace alias cannot be used.
      Add default file-event_handler callbacks. #2374

Loren Burkholder (1):
      Add openSUSE installation

Lucas CHOLLET (1):
      Expend support for any std::chrono::duration in `spdlog::flush_every`

Nicolas Benes (1):
      Use lower-case "windows.h" for case-sensitive file systems

Nigel Stewart (4):
      cmake: set(CMAKE_POSITION_INDEPENDENT_CODE ON) for Linux static library purposes
      SPDLOG_NO_SOURCE_LOC support for omitting __FILE__, __LINE__ and SPDLOG_FUNCTION information
      cmake: SPDLOG_BUILD_PIC opt-in for CMAKE_POSITION_INDEPENDENT_CODE
      SPDLOG_NO_SOURCE_LOC implementation refinement

Puneet Matharu (1):
      Export targets to build directory so that it can be found at configure time.

Rosen Penev (1):
      test_stopwatch: fix on mingw

Sandor Magyar (8):
      Catch exception by reference to fix -Wcatch-value warning
      Add numerical level to Mongo sink for easier queries
      Don't force Mongo sink to own MongoCXX instance
      Adjust MongoCXX instance handling in mongo_sink
      Remove pointless try block in mongo_sink
      Improve arg passing and exceptions in mongo_sink
      clang-format mongo_sink.h
      Change mongocxx::exception handler to std::exception

Shen-Ta Hsieh (1):
      Explicitly casting level_enum to size_t.

Simon-Janos (1):
      Re-introduce redundant std::move at return for old GCC (before version 5) inside an ifdef for e.g. CentOS 7

Timo Lange (2):
      use __android_log_write or __android_log_buf_write based on template paramter
      remove usage of forward args

bergen (2):
      update
      add overrun reset function

cookcocck (1):
      Set c++20 when SPDLOG_USE_STD_FORMAT option is turned on

espkk (1):
      Make file_event_handlers an aggregate

gabime (19):
      Use fmt::detail::vformat_to(buf, ...) since it is ~20ns faster than fmt::vformat_to(std::back_inserter(buf),..)
      clang-format
      Bump bundled fmtlib to version 1.9.1
      Renamed bench name
      suppress "integral constant overflow" warning under msvc 2017
      clang format
      Update user defined type example
      suppress warning 4307 when including format-inline.h under msvc 2017
      updated readme
      enable the ostream formatting for backward compatibility with fmt 8.x
      Replace  fmt::detail::vformat_to(buf,..) with  fmt::vformat_to(fmt::appender(buf)
      Replace  fmt::detail::vformat_to(buf,..) with  fmt::vformat_to(fmt::appender(buf)
      Rvert suppressing msvc2017 warnings and fix ci instead
      Fix fmt::vformat_to when SPDLOG_WCHAR_TO_UTF8_SUPPORT is defined
      Fix #2431
      Fixed syntax error from prev commit
      Fixed msvc warning C4800 in win_eventlog_sink
      Try again fixing fmt::vformat_to when SPDLOG_WCHAR_TO_UTF8_SUPPORT is defined
      Check IsDebuggerPresent in msvc_sink before doing work. Fix #2408

offa (6):
      Workaround GCC 12 warning
      Workaround deprecation warning on Clang with C++20
      Use pragams instead of compile options
      Migrate to Github Actions CI
      Remove .travis.yml
      Replace Travis CI Badge with Github Actions

panzhongxian (2):
      Remove try_lock from null_mutex.
      Romove the empty file if no log in first period in hourly logger

刘耘呈 (1):
      Use 'SPDLOG_FMT_RUNTIME' to fix compilation error throwed MSVC and fmt 9.1.x (#2517)